---
apiVersion: v1
kind: Pod
metadata:
  name: bird
  labels:
    app.kubernetes.io/name: bird
    app.kubernetes.io/version: "2.0.8"
spec:
  hostNetwork: true
  containers:
    - name: bird
      image: mazzy/bird:v2.0.8
      ports:
        - name: bind
          containerPort: 179
          protocol: TCP
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_BROADCAST
            - NET_RAW
