#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/bird \
	/var/log/bird

[[ ! -f /config/bird/bird.conf ]] && \
	cp /defaults/bird.conf /config/bird/bird.conf

# cleanup stale pid and sock files
[[ -e /var/run/bird/bird.pid || -e /var/run/bird/bird.ctl ]] && \
	rm -rf /var/run/bird/*

chown -R abc:abc \
	/config \
	/var/log/bird
